version: "3.7"
services:
    # image project
    # args->user = set your user
  app:
    build:
      args:
        user: pedropereira
        uid: 1000
        PHP_VERSION: '8.2-fpm'
      context: ./
      dockerfile: Dockerfile
    image: demo
    container_name: demo-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./application:/var/www
    networks:
      - demo

  db:
    image: mysql:5.7
    container_name: demo-mysql
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-homestead}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-minhasenhadificil}
      MYSQL_PASSWORD: ${DB_PASSWORD:-minhasenhadificil}
      MYSQL_USER: ${DB_USERNAME:-homestead}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - demo

  nginx:
    image: nginx:alpine
    container_name: demo-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./application:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - demo

  # redis
#  redis:
#    image: redis:latest
#    networks:
#        - demo
        
networks:
  demo:
    driver: bridge
